"use client";
import {useEffect,useMemo,useState} from 'react';
import PageHeader from '@/components/PageHeader';

type Tab='transactions'|'stock-card'|'warehouse-stock'|'rack-stock';
const tabs:[Tab,string,string][]=[
  ['transactions','Laporan Transaksi','Barang masuk, keluar, pindah gudang & pindah rak'],
  ['stock-card','Kartu Stok','Mutasi detail dan saldo sebelum/sesudah'],
  ['warehouse-stock','Stok per Gudang','Saldo setiap produk pada masing-masing gudang'],
  ['rack-stock','Stok per Rak','Saldo produk sampai lokasi rak/bin'],
];
const typeLabel:any={IN:'Barang Masuk',OUT:'Barang Keluar',WAREHOUSE_TRANSFER:'Pindah Gudang',RACK_TRANSFER:'Pindah Rak',TRANSFER_IN:'Transfer Masuk',TRANSFER_OUT:'Transfer Keluar',ADJUSTMENT:'Opname / Adjustment'};

export default function Reports(){
  const[tab,setTab]=useState<Tab>('transactions'); const[rows,setRows]=useState<any[]>([]);const[loading,setLoading]=useState(false);
  const[products,setProducts]=useState<any[]>([]),[warehouses,setWarehouses]=useState<any[]>([]),[locations,setLocations]=useState<any[]>([]);
  const[filters,setFilters]=useState({from:'',to:'',product_id:'',warehouse_id:'',location_id:'',type:''});
  useEffect(()=>{Promise.all([fetch('/api/products').then(r=>r.json()),fetch('/api/warehouses').then(r=>r.json()),fetch('/api/locations').then(r=>r.json())]).then(([p,w,l])=>{setProducts(Array.isArray(p)?p:[]);setWarehouses(Array.isArray(w)?w:[]);setLocations(Array.isArray(l)?l:[])})},[]);
  const filteredLocations=useMemo(()=>filters.warehouse_id?locations.filter((l:any)=>l.warehouse_id===filters.warehouse_id):locations,[locations,filters.warehouse_id]);
  async function load(){setLoading(true);const q=new URLSearchParams({report:tab});Object.entries(filters).forEach(([k,v])=>v&&q.set(k,v));try{const x=await fetch('/api/reports?'+q).then(r=>r.json());setRows(Array.isArray(x)?x:[])}finally{setLoading(false)}}
  useEffect(()=>{load()},[tab]);
  function reset(){setFilters({from:'',to:'',product_id:'',warehouse_id:'',location_id:'',type:''});setTimeout(load,0)}
  function exportCsv(){if(!rows.length)return;const keys=Object.keys(rows[0]);const esc=(v:any)=>`"${String(v??'').replaceAll('"','""')}"`;const csv=[keys.join(','),...rows.map(r=>keys.map(k=>esc(r[k])).join(','))].join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download=`wms-acis-${tab}-${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(a.href)}
  const totalQty=rows.reduce((s,r)=>s+Number(r.qty||0),0);
  return <><PageHeader title="Laporan" subtitle="Analisis transaksi, kartu stok, stok per gudang dan stok per rak" actions={<button className="btn btn-secondary" onClick={exportCsv} disabled={!rows.length}>⇩ Export CSV</button>}/>
    <div className="report-tabs">{tabs.map(([id,title,desc])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}><strong>{title}</strong><span>{desc}</span></button>)}</div>
    <section className="card report-filter"><div className="form-grid report-filter-grid">
      {(tab==='transactions'||tab==='stock-card')&&<label>Dari tanggal<input type="date" value={filters.from} onChange={e=>setFilters({...filters,from:e.target.value})}/></label>}
      {(tab==='transactions'||tab==='stock-card')&&<label>Sampai tanggal<input type="date" value={filters.to} onChange={e=>setFilters({...filters,to:e.target.value})}/></label>}
      <label>Produk<select value={filters.product_id} onChange={e=>setFilters({...filters,product_id:e.target.value})}><option value="">Semua produk</option>{products.map((p:any)=><option key={p.id} value={p.id}>{p.sku} — {p.name}</option>)}</select></label>
      <label>Gudang<select value={filters.warehouse_id} onChange={e=>setFilters({...filters,warehouse_id:e.target.value,location_id:''})}><option value="">Semua gudang</option>{warehouses.map((w:any)=><option key={w.id} value={w.id}>{w.code} — {w.name}</option>)}</select></label>
      {(tab==='stock-card'||tab==='rack-stock')&&<label>Rak / lokasi<select value={filters.location_id} onChange={e=>setFilters({...filters,location_id:e.target.value})}><option value="">Semua rak</option>{filteredLocations.map((l:any)=><option key={l.id} value={l.id}>{l.code} — {l.name}</option>)}</select></label>}
      {tab==='transactions'&&<label>Jenis transaksi<select value={filters.type} onChange={e=>setFilters({...filters,type:e.target.value})}><option value="">Semua transaksi</option><option value="IN">Barang Masuk</option><option value="OUT">Barang Keluar</option><option value="WAREHOUSE_TRANSFER">Pindah Gudang</option><option value="RACK_TRANSFER">Pindah Rak</option></select></label>}
    </div><div className="report-filter-actions"><button className="btn btn-primary" onClick={load}>Tampilkan</button><button className="btn btn-secondary" onClick={reset}>Reset</button></div></section>
    <div className="report-summary"><div><span>Baris laporan</span><strong>{rows.length.toLocaleString('id-ID')}</strong></div><div><span>Total qty pada tampilan</span><strong>{totalQty.toLocaleString('id-ID')}</strong></div><div><span>Jenis laporan</span><strong>{tabs.find(x=>x[0]===tab)?.[1]}</strong></div></div>
    <section className="card"><div className="card-head"><div><h2>{tabs.find(x=>x[0]===tab)?.[1]}</h2><p>{loading?'Memuat data...':`${rows.length} baris ditemukan`}</p></div></div><div className="table-wrap">{tab==='transactions'?<Transactions rows={rows}/>:tab==='stock-card'?<StockCard rows={rows}/>:tab==='warehouse-stock'?<WarehouseStock rows={rows}/>:<RackStock rows={rows}/>}</div></section>
  </>}

function Empty(){return <tr><td colSpan={12}><div className="empty-report">Belum ada data untuk filter ini.</div></td></tr>}
function Transactions({rows}:{rows:any[]}){return <table className="table"><thead><tr><th>Tanggal</th><th>No. Transaksi</th><th>Jenis</th><th>Produk</th><th>Asal</th><th>Tujuan</th><th>Qty</th><th>Referensi</th><th>Petugas</th></tr></thead><tbody>{!rows.length?<Empty/>:rows.map(r=><tr key={r.id}><td>{new Date(r.operation_date).toLocaleString('id-ID')}</td><td className="mono">{r.operation_no}</td><td><span className="badge">{typeLabel[r.type]||r.type}</span></td><td><strong>{r.product_name}</strong><div className="muted">{r.sku}</div></td><td>{r.source_warehouse?<><strong>{r.source_warehouse}</strong><div className="muted">{r.source_location_code} · {r.source_location}</div></>:'-'}</td><td>{r.destination_warehouse?<><strong>{r.destination_warehouse}</strong><div className="muted">{r.destination_location_code} · {r.destination_location}</div></>:'-'}</td><td><strong>{r.qty} {r.unit}</strong></td><td>{r.reference||'-'}<div className="muted">{r.note||''}</div></td><td>{r.actor}</td></tr>)}</tbody></table>}
function StockCard({rows}:{rows:any[]}){return <table className="table"><thead><tr><th>Waktu</th><th>Produk</th><th>Gudang / Rak</th><th>Mutasi</th><th>Qty</th><th>Saldo Sebelum</th><th>Saldo Sesudah</th><th>No. Transaksi</th><th>Petugas</th></tr></thead><tbody>{!rows.length?<Empty/>:rows.map(r=><tr key={r.id}><td>{new Date(r.created_at).toLocaleString('id-ID')}</td><td><strong>{r.product_name}</strong><div className="muted">{r.sku}</div></td><td><strong>{r.warehouse_name||'-'}</strong><div className="muted">{r.location_code||'-'} · {r.location_name||'-'}</div></td><td><span className="badge">{typeLabel[r.type]||r.type}</span></td><td>{r.qty} {r.unit}</td><td>{r.before_qty}</td><td><strong>{r.after_qty}</strong></td><td className="mono">{r.operation_no||'-'}<div className="muted">{r.reference||''}</div></td><td>{r.actor}</td></tr>)}</tbody></table>}
function WarehouseStock({rows}:{rows:any[]}){return <table className="table"><thead><tr><th>Gudang</th><th>SKU</th><th>Produk</th><th>Kategori</th><th>Saldo</th></tr></thead><tbody>{!rows.length?<Empty/>:rows.map((r,i)=><tr key={`${r.warehouse_id}-${r.product_id}-${i}`}><td><strong>{r.warehouse_name}</strong><div className="muted">{r.warehouse_code}</div></td><td className="mono">{r.sku}</td><td><strong>{r.product_name}</strong></td><td>{r.category||'-'}</td><td><strong>{r.qty.toLocaleString('id-ID')} {r.unit}</strong></td></tr>)}</tbody></table>}
function RackStock({rows}:{rows:any[]}){return <table className="table"><thead><tr><th>Gudang</th><th>Rak / Lokasi</th><th>SKU</th><th>Produk</th><th>Kategori</th><th>Saldo</th><th>Update</th></tr></thead><tbody>{!rows.length?<Empty/>:rows.map((r,i)=><tr key={`${r.location_id}-${r.product_id}-${i}`}><td><strong>{r.warehouse_name||'-'}</strong><div className="muted">{r.warehouse_code||'-'}</div></td><td><strong>{r.location_code}</strong><div className="muted">{r.location_name}</div></td><td className="mono">{r.sku}</td><td><strong>{r.product_name}</strong></td><td>{r.category||'-'}</td><td><strong>{r.qty.toLocaleString('id-ID')} {r.unit}</strong></td><td>{new Date(r.updated_at).toLocaleString('id-ID')}</td></tr>)}</tbody></table>}
