"use client";
import {FormEvent,useEffect,useMemo,useState} from 'react';
import Link from 'next/link';
import PageHeader from '@/components/PageHeader';

type Outbound={id:string;operation_no:string;operation_date:string;qty:number;reference?:string;sku:string;product_name:string;unit:string;warehouse_name?:string;location_code?:string;packing_list_id?:string;packing_no?:string};
const statuses=['DRAFT','PACKED','SHIPPED','CANCELLED'] as const;
const labels:any={DRAFT:'Draft',PACKED:'Packed',SHIPPED:'Shipped',CANCELLED:'Cancelled'};
export default function PackingListPage(){
 const[rows,setRows]=useState<any[]>([]),[outs,setOuts]=useState<Outbound[]>([]),[open,setOpen]=useState(false),[editing,setEditing]=useState<any>(null),[selected,setSelected]=useState<string[]>([]),[msg,setMsg]=useState(''),[saving,setSaving]=useState(false),[q,setQ]=useState('');
 const load=()=>Promise.all([fetch('/api/packing-lists').then(r=>r.json()),fetch('/api/packing-lists?available=1').then(r=>r.json())]).then(([a,b])=>{setRows(a);setOuts(b)});useEffect(()=>{load()},[]);
 const selectable=useMemo(()=>outs.filter(o=>!o.packing_list_id||o.packing_list_id===editing?.id).filter(o=>!q||`${o.operation_no} ${o.sku} ${o.product_name} ${o.reference||''}`.toLowerCase().includes(q.toLowerCase())),[outs,editing,q]);
 async function edit(r:any){setMsg('');const d=await fetch('/api/packing-lists?id='+r.id).then(x=>x.json());setEditing(d);setSelected((d.items||[]).map((x:any)=>x.operation_id));setOpen(true)}
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();setSaving(true);setMsg('');const b:any=Object.fromEntries(new FormData(e.currentTarget));b.operation_ids=selected;b.id=editing?.id;const r=await fetch('/api/packing-lists',{method:editing?'PUT':'POST',headers:{'content-type':'application/json'},body:JSON.stringify(b)});const j=await r.json();setSaving(false);if(!r.ok)return setMsg(j.error||'Gagal menyimpan');setOpen(false);setEditing(null);setSelected([]);setMsg('Packing list berhasil disimpan');load()}
 async function del(id:string){if(!confirm('Hapus packing list ini? Transaksi stok tidak akan berubah.'))return;const r=await fetch('/api/packing-lists?id='+id,{method:'DELETE'});const j=await r.json();if(!r.ok)return setMsg(j.error||'Gagal menghapus');setMsg('Packing list berhasil dihapus');load()}
 const toggle=(id:string)=>setSelected(v=>v.includes(id)?v.filter(x=>x!==id):[...v,id]);
 return <><PageHeader title="Packing List" subtitle="Kelompokkan Barang Keluar menjadi dokumen packing untuk proses pengepakan dan pengiriman." actions={<button className="btn btn-primary" onClick={()=>{setEditing(null);setSelected([]);setOpen(true)}}>＋ Buat Packing List</button>}/>
 {msg&&<div className={msg.includes('berhasil')?'notice success-notice':'notice error'}>{msg}</div>}
 <div className="packing-kpis"><div><span>Total Packing List</span><strong>{rows.length}</strong></div><div><span>Menunggu Dipacking</span><strong>{rows.filter(x=>x.status==='DRAFT').length}</strong></div><div><span>Sudah Packed</span><strong>{rows.filter(x=>x.status==='PACKED').length}</strong></div><div><span>Sudah Dikirim</span><strong>{rows.filter(x=>x.status==='SHIPPED').length}</strong></div></div>
 <section className="card"><div className="card-head"><div><h2>Daftar Packing List</h2><p>{rows.length} dokumen tercatat</p></div></div><div className="table-wrap"><table className="table"><thead><tr><th>No. Packing</th><th>Tanggal</th><th>Penerima</th><th>Referensi</th><th>Isi</th><th>Gudang</th><th>Status</th><th className="actions-col">Aksi</th></tr></thead><tbody>{rows.length?rows.map(r=><tr key={r.id}><td><strong className="mono">{r.packing_no}</strong></td><td>{new Date(r.created_at).toLocaleString('id-ID',{dateStyle:'medium',timeStyle:'short'})}</td><td><strong>{r.recipient_name}</strong><div className="cell-sub">{r.recipient_company||r.recipient_phone||'-'}</div></td><td>{r.reference||'-'}</td><td><strong>{r.item_count} item</strong><div className="cell-sub">{r.total_qty} total qty</div></td><td>{r.warehouses||'-'}</td><td><span className={`packing-status ${r.status.toLowerCase()}`}>{labels[r.status]}</span></td><td><div className="row-actions"><Link className="icon-btn" title="Lihat / Cetak" href={`/packing-list/${r.id}`}>▤</Link><button className="icon-btn" title="Edit" onClick={()=>edit(r)}>✎</button><button className="icon-btn danger-btn" title="Hapus" onClick={()=>del(r.id)}>⌫</button></div></td></tr>):<tr><td colSpan={8}><div className="empty-state">Belum ada packing list.</div></td></tr>}</tbody></table></div></section>
 {open&&<div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setOpen(false)}}><div className="modal packing-modal"><div className="modal-head"><div><h2>{editing?'Edit':'Buat'} Packing List</h2><p>Pilih transaksi Barang Keluar yang akan dipacking bersama.</p></div><button className="icon-btn" onClick={()=>setOpen(false)}>×</button></div><form onSubmit={save} className="form-grid">
 <div className="field"><label>Nama Penerima *</label><input name="recipient_name" required defaultValue={editing?.recipient_name||''}/></div><div className="field"><label>Perusahaan</label><input name="recipient_company" defaultValue={editing?.recipient_company||''}/></div><div className="field"><label>No. Telepon</label><input name="recipient_phone" defaultValue={editing?.recipient_phone||''}/></div><div className="field"><label>Referensi</label><input name="reference" defaultValue={editing?.reference||''} placeholder="SO / DO / PO pelanggan"/></div><div className="field span2"><label>Alamat Pengiriman</label><textarea name="address" rows={2} defaultValue={editing?.address||''}/></div><div className="field"><label>Status</label><select name="status" defaultValue={editing?.status||'DRAFT'}>{statuses.map(s=><option key={s} value={s}>{labels[s]}</option>)}</select></div><div className="field"><label>Petugas Packing</label><input name="packed_by" defaultValue={editing?.packed_by||'Admin Gudang'}/></div><div className="field span2"><label>Catatan</label><input name="notes" defaultValue={editing?.notes||''}/></div>
 <div className="field span2 packing-picker"><div className="packing-picker-head"><div><label>Barang Keluar yang dipacking *</label><small>{selected.length} transaksi dipilih</small></div><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Cari nomor transaksi / SKU / produk..."/></div><div className="packing-select-list">{selectable.length?selectable.map(o=><label key={o.id} className={`packing-select ${selected.includes(o.id)?'selected':''}`}><input type="checkbox" checked={selected.includes(o.id)} onChange={()=>toggle(o.id)}/><div><strong>{o.product_name}</strong><span>{o.sku} · {o.operation_no}</span><small>{o.warehouse_name||'-'} / {o.location_code||'-'} · {o.qty} {o.unit}{o.reference?` · Ref ${o.reference}`:''}</small></div></label>):<div className="empty-state">Tidak ada transaksi Barang Keluar yang tersedia.</div>}</div></div>
 <div className="span2 modal-actions"><button type="button" className="btn btn-secondary" onClick={()=>setOpen(false)}>Batal</button><button className="btn btn-primary" disabled={saving||selected.length===0}>{saving?'Menyimpan...':'Simpan Packing List'}</button></div></form></div></div>}</>
}
