"use client";
import {useEffect,useState} from "react";
import Link from "next/link";

type Data={kpi:{total_sku:number;total_stock:number;low_stock:number;incoming:number;outgoing:number};lowStock:any[];movements:any[]};
export default function Dashboard(){const[d,setD]=useState<Data|null>(null);const[err,setErr]=useState("");useEffect(()=>{fetch('/api/dashboard').then(r=>r.json()).then(setD).catch(()=>setErr('Gagal memuat dashboard'))},[]);return <>
<div className="topbar"><div><h1 className="title">Dashboard Gudang</h1><div className="muted">Ringkasan inventory hari ini</div></div><input className="search" placeholder="Cari SKU, nama produk, atau barcode..." onKeyDown={e=>{if(e.key==='Enter')location.href='/products?q='+encodeURIComponent((e.target as HTMLInputElement).value)}}/></div>
{err&&<div className="notice error">{err}</div>}{!d?<div className="card">Memuat...</div>:<><div className="cards">
{[['Total SKU',d.kpi.total_sku],['Total Stock',d.kpi.total_stock],['Low Stock',d.kpi.low_stock],['Barang Masuk',`+${d.kpi.incoming}`],['Barang Keluar',`-${d.kpi.outgoing}`]].map(([l,v])=><div className="card" key={l as string}><div className="kpi-label">{l}</div><div className="kpi-value">{v}</div></div>)}</div>
<div className="page-actions" style={{marginTop:18}}><Link className="btn btn-blue" href="/scan">▥ Scan Barang</Link><Link className="btn btn-light" href="/products">+ Produk</Link></div>
<div className="grid2"><section className="card"><div className="section-head"><h2>⚠ Low Stock</h2><Link className="muted" href="/stock">Lihat semua</Link></div><div className="table-wrap"><table className="table"><thead><tr><th>Produk</th><th>SKU</th><th>Lokasi</th><th>Sisa</th></tr></thead><tbody>{d.lowStock.length?d.lowStock.map((p:any)=><tr key={p.id}><td><strong>{p.name}</strong></td><td>{p.sku}</td><td><span className="badge">{p.locations||'-'}</span></td><td className="danger">{p.total_stock} pcs</td></tr>):<tr><td colSpan={4} className="empty">Tidak ada stok menipis 🎉</td></tr>}</tbody></table></div></section>
<section className="card"><div className="section-head"><h2>Riwayat Pergerakan</h2><Link className="muted" href="/history">Lihat semua</Link></div>{d.movements.length?d.movements.map((m:any)=><div className="movement" key={m.id}><div><strong>{label(m.type)} · {m.name}</strong><span className="muted">{m.location_name||'-'} · {new Date(m.created_at).toLocaleString('id-ID')}</span></div><strong className={m.type.includes('OUT')?'danger':'success'}>{m.type.includes('OUT')?'-':'+'}{m.qty}</strong></div>):<div className="empty">Belum ada transaksi.</div>}</section></div></>}</>}
function label(t:string){return({IN:'Barang Masuk',OUT:'Barang Keluar',ADJUSTMENT:'Adjustment',TRANSFER_IN:'Transfer Masuk',TRANSFER_OUT:'Transfer Keluar'} as any)[t]||t}
