"use client";
import {FormEvent,useEffect,useMemo,useState} from 'react'; import PageHeader from './PageHeader'; 
type OpType='IN'|'OUT'|'WAREHOUSE_TRANSFER'|'RACK_TRANSFER';
type P={id:string;sku:string;name:string;unit:string;total_stock:number}; type L={id:string;code:string;name:string;warehouse_id:string;warehouse_name:string};
const cfg={IN:{title:'Barang Masuk',sub:'Penerimaan stok ke gudang dan rak tujuan'},OUT:{title:'Barang Keluar',sub:'Pengeluaran stok dari lokasi penyimpanan'},WAREHOUSE_TRANSFER:{title:'Pindah Gudang',sub:'Transfer stok antar gudang dengan jejak transaksi lengkap'},RACK_TRANSFER:{title:'Pindah Rak',sub:'Relokasi stok antar rak dalam gudang yang sama'}} as const;
export default function OperationsPage({type}:{type:OpType}){const[prefillProduct,setPrefillProduct]=useState(''),[selectedProduct,setSelectedProduct]=useState('');const[rows,setRows]=useState<any[]>([]),[products,setProducts]=useState<P[]>([]),[locations,setLocations]=useState<L[]>([]),[companies,setCompanies]=useState<any[]>([]),[editing,setEditing]=useState<any>(null),[open,setOpen]=useState(false),[msg,setMsg]=useState('');
useEffect(()=>{const q=new URLSearchParams(window.location.search);const p=q.get('product')||'';if(p){setPrefillProduct(p);setSelectedProduct(p)}if(q.get('open')==='1'&&p){setEditing(null);setOpen(true)}},[]);
const load=()=>Promise.all([fetch('/api/operations?type='+type).then(r=>r.json()),fetch('/api/products').then(r=>r.json()),fetch('/api/locations').then(r=>r.json()),fetch('/api/companies').then(r=>r.json())]).then(([a,b,c,d])=>{setRows(a);setProducts(b);setLocations(c);setCompanies(d)});useEffect(()=>{load()},[type]);
const warehouses=useMemo<[string,string][]>(()=>Array.from(new Map<string,string>(locations.filter(x=>x.warehouse_id).map(x=>[x.warehouse_id,x.warehouse_name] as [string,string])).entries()),[locations]);
async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();setMsg('');const body:any=Object.fromEntries(new FormData(e.currentTarget));body.type=type;const r=await fetch('/api/operations',{method:editing?'PUT':'POST',headers:{'content-type':'application/json'},body:JSON.stringify({...body,id:editing?.id})});const j=await r.json();if(!r.ok)return setMsg(j.error||'Gagal menyimpan');setOpen(false);setEditing(null);setMsg('Transaksi berhasil disimpan');load()}
async function del(id:string){if(!confirm('Hapus transaksi ini? Stok akan dikembalikan otomatis ke kondisi sebelum transaksi.'))return;const r=await fetch('/api/operations?id='+id,{method:'DELETE'});const j=await r.json();if(!r.ok)return setMsg(j.error||'Gagal menghapus');setMsg('Transaksi berhasil dihapus');load()}
function edit(r:any){setEditing(r);setSelectedProduct(r.product_id||'');setOpen(true)}
return <><PageHeader title={cfg[type].title} subtitle={cfg[type].sub} actions={<button className="btn btn-primary" onClick={()=>{setEditing(null);setSelectedProduct(prefillProduct||'');setOpen(true)}}>＋ Tambah Transaksi</button>}/>{msg&&<div className={msg.includes('berhasil')?'notice success-notice':'notice error'}>{msg}</div>}
<section className="card"><div className="card-head"><div><h2>Daftar {cfg[type].title}</h2><p>{rows.length} transaksi tercatat</p></div></div><div className="table-wrap"><table className="table"><thead><tr><th>No. Transaksi</th><th>Company</th><th>Tanggal</th><th>Produk</th>{type!=='IN'&&<th>Dari</th>}{type!=='OUT'&&<th>Ke</th>}<th>Qty</th><th>Referensi</th><th className="actions-col">Aksi</th></tr></thead><tbody>{rows.length?rows.map(r=><tr key={r.id}><td><span className="mono">{r.operation_no}</span></td><td><strong>{r.company_name}</strong><div className="cell-sub">{r.company_code}</div></td><td>{new Date(r.operation_date).toLocaleString('id-ID',{dateStyle:'medium',timeStyle:'short'})}</td><td><strong>{r.product_name}</strong><div className="cell-sub">{r.sku}</div></td>{type!=='IN'&&<td>{r.source_warehouse&&<div className="cell-sub">{r.source_warehouse}</div>}<strong>{r.source_location||'-'}</strong></td>}{type!=='OUT'&&<td>{r.destination_warehouse&&<div className="cell-sub">{r.destination_warehouse}</div>}<strong>{r.destination_location||'-'}</strong></td>}<td><span className={type==='OUT'?'qty out':'qty in'}>{type==='OUT'?'-':'+'}{r.qty} {r.unit}</span></td><td>{r.reference||'-'}</td><td><div className="row-actions"><button className="icon-btn" title="Edit" onClick={()=>edit(r)}>✎</button><button className="icon-btn danger-btn" title="Hapus" onClick={()=>del(r.id)}>⌫</button></div></td></tr>):<tr><td colSpan={8}><div className="empty-state">Belum ada transaksi {cfg[type].title.toLowerCase()}.</div></td></tr>}</tbody></table></div></section>
{open&&<div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget){setOpen(false);setEditing(null)}}}><div className="modal"><div className="modal-head"><div><h2>{editing?'Edit':'Tambah'} {cfg[type].title}</h2><p>Perubahan stok dilakukan otomatis saat disimpan.</p></div><button className="icon-btn" onClick={()=>{setOpen(false);setEditing(null)}}>×</button></div><form onSubmit={save} className="form-grid">
<div className="field span2"><label>Company / Perusahaan *</label><select name="company_id" required defaultValue={editing?.company_id||companies[0]?.id||''}><option value="">Pilih perusahaan</option>{companies.map(c=><option key={c.id} value={c.id}>{c.code} — {c.name}</option>)}</select></div>
<div className="field span2"><label>Produk *</label><select name="product_id" required value={selectedProduct} onChange={e=>setSelectedProduct(e.target.value)}><option value="">Pilih produk</option>{products.map(p=><option key={p.id} value={p.id}>{p.sku} — {p.name} (stok {p.total_stock})</option>)}</select>{prefillProduct&&selectedProduct===prefillProduct&&<small className="field-hint success-hint">✓ Produk otomatis dipilih dari hasil scan</small>}</div>
{type!=='IN'&&<LocationPicker label="Lokasi asal *" name="source_location_id" locations={locations} warehouses={warehouses} defaultValue={editing?.source_location_id}/>} {type!=='OUT'&&<LocationPicker label="Lokasi tujuan *" name="destination_location_id" locations={locations} warehouses={warehouses} defaultValue={editing?.destination_location_id}/>} 
<div className="field"><label>No. Transaksi</label><input name="operation_no" defaultValue={editing?.operation_no||''} placeholder="Otomatis jika kosong"/></div><div className="field"><label>Tanggal Transaksi *</label><input name="operation_date" type="datetime-local" required defaultValue={editing?new Date(new Date(editing.operation_date).getTime()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,16):new Date(Date.now()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,16)}/></div><div className="field"><label>Qty *</label><input name="qty" type="number" min="1" required defaultValue={editing?.qty||1}/></div><div className="field"><label>Referensi</label><input name="reference" defaultValue={editing?.reference||''} placeholder="PO / SO / dokumen"/></div><div className="field"><label>Catatan</label><input name="note" defaultValue={editing?.note||''} placeholder="Opsional"/></div><div className="span2 modal-actions"><button type="button" className="btn btn-secondary" onClick={()=>setOpen(false)}>Batal</button><button className="btn btn-primary">Simpan Transaksi</button></div></form></div></div>}</>}
function LocationPicker({label,name,locations,warehouses,defaultValue}:{label:string;name:string;locations:L[];warehouses:[string,string][];defaultValue?:string}){return <div className="field"><label>{label}</label><select name={name} required defaultValue={defaultValue||''}><option value="">Pilih lokasi</option>{warehouses.map(([wid,wname])=><optgroup key={wid} label={wname}>{locations.filter(l=>l.warehouse_id===wid).map(l=><option key={l.id} value={l.id}>{l.code} — {l.name}</option>)}</optgroup>)}</select></div>}
