"use client";
import {FormEvent,useEffect,useState} from 'react';
import PageHeader from '@/components/PageHeader';
const today=()=>new Date().toISOString().slice(0,10);
export default function Picking(){
 const[rows,setRows]=useState<any[]>([]),[products,setProducts]=useState<any[]>([]),[locations,setLocations]=useState<any[]>([]),[companies,setCompanies]=useState<any[]>([]),[open,setOpen]=useState(false),[items,setItems]=useState<any[]>([{product_id:'',source_location_id:'',qty:1}]),[msg,setMsg]=useState(''),[prefill,setPrefill]=useState('');
 const load=()=>Promise.all([fetch('/api/picking-lists').then(r=>r.json()),fetch('/api/products').then(r=>r.json()),fetch('/api/locations').then(r=>r.json()),fetch('/api/companies').then(r=>r.json())]).then(([a,b,c,d])=>{setRows(a);setProducts(b);setLocations(c);setCompanies(d)});
 useEffect(()=>{load();const q=new URLSearchParams(window.location.search),p=q.get('product')||'';if(p){setPrefill(p);setItems([{product_id:p,source_location_id:'',qty:1}]);if(q.get('open')==='1')setOpen(true)}},[]);
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();const b:any=Object.fromEntries(new FormData(e.currentTarget));b.items=items;const r=await fetch('/api/picking-lists',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(b)}),j=await r.json();if(!r.ok)return setMsg(j.error);setOpen(false);setItems([{product_id:'',source_location_id:'',qty:1}]);setMsg('Picking List berhasil dibuat');load()}
 async function complete(id:string){if(!confirm('Selesaikan picking? Stok akan berkurang dan Barang Keluar dibuat otomatis.'))return;const r=await fetch('/api/picking-lists',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'complete',id})}),j=await r.json();if(!r.ok)return setMsg(j.error);setMsg('Picking selesai. Barang Keluar siap masuk Packing List.');load()}
 async function del(id:string){if(!confirm('Hapus picking list?'))return;const r=await fetch('/api/picking-lists?id='+id,{method:'DELETE'}),j=await r.json();if(!r.ok)return setMsg(j.error);load()}
 function addNew(){setItems([{product_id:prefill||'',source_location_id:'',qty:1}]);setOpen(true)}
 return <><PageHeader title="Picking List" subtitle="Siapkan barang dari rak sebelum packing. Complete Picking otomatis membuat transaksi Barang Keluar." actions={<button className="btn btn-primary" onClick={addNew}>＋ Buat Picking</button>}/>{msg&&<div className={msg.includes('berhasil')||msg.includes('selesai')?'notice success-notice':'notice error'}>{msg}</div>}
 <section className="card"><div className="card-head"><div><h2>Daftar Picking</h2><p>{rows.length} dokumen</p></div></div><div className="table-wrap"><table className="table"><thead><tr><th>No Picking</th><th>Tanggal</th><th>Company</th><th>Referensi</th><th>Customer</th><th>Item / Qty</th><th>Status</th><th>Aksi</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td className="mono">{r.picking_no}</td><td>{new Date(r.picking_date||r.created_at).toLocaleDateString('id-ID',{dateStyle:'medium'})}</td><td><strong>{r.company_name}</strong><div className="cell-sub">{r.company_code}</div></td><td>{r.reference||'-'}</td><td>{r.customer_name||'-'}</td><td>{r.item_count} item · {r.total_qty} qty</td><td><span className={'packing-status '+String(r.status).toLowerCase()}>{r.status}</span></td><td><div className="row-actions">{r.status!=='PICKED'&&r.status!=='CANCELLED'&&<button className="btn-mini" onClick={()=>complete(r.id)}>Complete</button>}<button className="icon-btn danger-btn" onClick={()=>del(r.id)}>⌫</button></div></td></tr>)}</tbody></table></div></section>
 {open&&<div className="modal-backdrop"><div className="modal packing-modal"><div className="modal-head"><div><h2>Buat Picking List</h2><p>Pilih produk, rak asal dan qty.</p></div><button className="icon-btn" onClick={()=>setOpen(false)}>×</button></div><form onSubmit={save} className="form-grid"><div className="field"><label>No. Picking</label><input name="picking_no" placeholder="Otomatis jika kosong"/></div><div className="field"><label>Tanggal Transaksi *</label><input name="picking_date" type="date" required defaultValue={today()}/></div><div className="field span2"><label>Company *</label><select name="company_id" required defaultValue=""><option value="">Pilih perusahaan</option>{companies.map(c=><option key={c.id} value={c.id}>{c.code} — {c.name}</option>)}</select></div><div className="field"><label>Referensi / SO</label><input name="reference"/></div><div className="field"><label>Customer</label><input name="customer_name"/></div><div className="field span2"><label>Catatan</label><input name="notes"/></div><div className="span2 line-items"><div className="card-head"><h3>Item Picking</h3><button type="button" className="btn btn-secondary" onClick={()=>setItems(v=>[...v,{product_id:'',source_location_id:'',qty:1}])}>＋ Item</button></div>{items.map((it,i)=><div className="line-item-row picking-line" key={i}><select value={it.product_id} onChange={e=>setItems(v=>v.map((x,j)=>j===i?{...x,product_id:e.target.value}:x))} required><option value="">Produk</option>{products.map(p=><option value={p.id} key={p.id}>{p.sku} — {p.name}</option>)}</select><select value={it.source_location_id} onChange={e=>setItems(v=>v.map((x,j)=>j===i?{...x,source_location_id:e.target.value}:x))} required><option value="">Rak asal</option>{locations.map(l=><option value={l.id} key={l.id}>{l.warehouse_name} / {l.code}</option>)}</select><input type="number" min="1" value={it.qty} onChange={e=>setItems(v=>v.map((x,j)=>j===i?{...x,qty:Number(e.target.value)}:x))}/><button type="button" className="icon-btn danger-btn" onClick={()=>setItems(v=>v.filter((_,j)=>j!==i))}>×</button></div>)}</div>{prefill&&items[0]?.product_id===prefill&&<div className="span2 notice success-notice">✓ Produk otomatis dipilih dari hasil scan barcode/QR.</div>}<div className="span2 modal-actions"><button type="button" className="btn btn-secondary" onClick={()=>setOpen(false)}>Batal</button><button className="btn btn-primary">Simpan Picking</button></div></form></div></div>}</>}
