"use client";
import{useEffect,useRef,useState}from"react";import PageHeader from"@/components/PageHeader";import type{Product,Location}from"@/lib/types";
export default function Scan(){const videoRef=useRef<HTMLVideoElement>(null);const streamRef=useRef<MediaStream|null>(null);const timerRef=useRef<any>(null);const[code,setCode]=useState('');const[product,setProduct]=useState<Product|null>(null);const[locations,setLocations]=useState<Location[]>([]);const[loc,setLoc]=useState('');const[qty,setQty]=useState(1);const[msg,setMsg]=useState('');const[running,setRunning]=useState(false);
useEffect(()=>{fetch('/api/locations').then(r=>r.json()).then((x:Location[])=>{setLocations(x);if(x[0])setLoc(x[0].id)});return()=>stopCamera()},[]);
async function lookup(raw:string){const v=raw.trim();if(!v)return;setCode(v);setMsg('');const r=await fetch('/api/products?barcode='+encodeURIComponent(v));const rows=await r.json();if(rows[0]){setProduct(rows[0]);return}const r2=await fetch('/api/products?q='+encodeURIComponent(v));const rows2=await r2.json();setProduct(rows2[0]||null);if(!rows2[0])setMsg('Produk tidak ditemukan. Tambahkan barcode di menu Produk.')}
async function startCamera(){setMsg('');const BD=(window as any).BarcodeDetector;if(!BD){setMsg('Browser ini belum mendukung scan kamera native. Gunakan Chrome/Edge Android, scanner USB, atau input manual.');return}try{const stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}},audio:false});streamRef.current=stream;if(videoRef.current){videoRef.current.srcObject=stream;await videoRef.current.play()}setRunning(true);const detector=new BD({formats:['ean_13','ean_8','code_128','code_39','upc_a','upc_e','qr_code']});timerRef.current=setInterval(async()=>{if(!videoRef.current)return;try{const codes=await detector.detect(videoRef.current);if(codes?.[0]?.rawValue){await lookup(codes[0].rawValue);stopCamera()}}catch{}},500)}catch{setMsg('Kamera tidak bisa dibuka. Pastikan izin kamera diberikan dan situs memakai HTTPS.') }}
function stopCamera(){if(timerRef.current)clearInterval(timerRef.current);timerRef.current=null;streamRef.current?.getTracks().forEach(t=>t.stop());streamRef.current=null;setRunning(false)}
async function move(type:'IN'|'OUT'){if(!product||!loc||qty<1)return;const r=await fetch('/api/operations',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({product_id:product.id,type,qty,source_location_id:type==='OUT'?loc:null,destination_location_id:type==='IN'?loc:null,note:'Transaksi dari halaman Scan'})});const j=await r.json();if(!r.ok)return setMsg(j.error);setMsg(type==='IN'?`+${qty} berhasil ditambahkan`:`-${qty} berhasil dikeluarkan`);lookup(product.barcode||product.sku)}
return <><PageHeader title="Scan Barang" subtitle="Kamera, scanner USB, atau input barcode manual"/><div className="scan-wrap"><section className="video-box"><video ref={videoRef} muted playsInline/><div className="scan-line"/><div style={{position:'absolute',bottom:18,display:'flex',gap:8}}><button className="btn btn-blue" onClick={running?stopCamera:startCamera}>{running?'Stop Kamera':'Buka Kamera'}</button></div></section><section className="card product-result"><div className="field"><label>Barcode / SKU</label><div style={{display:'flex',gap:8}}><input style={{flex:1}} autoFocus value={code} onChange={e=>setCode(e.target.value)} onKeyDown={e=>e.key==='Enter'&&lookup(code)} placeholder="Scan di sini..."/><button className="btn btn-light" onClick={()=>lookup(code)}>Cari</button></div></div>{product?<><hr style={{border:0,borderTop:'1px solid var(--line)',margin:'18px 0'}}/><h2>{product.name}</h2><p><strong>SKU:</strong> {product.sku}<br/><strong>Barcode:</strong> {product.barcode||'-'}<br/><strong>Stok total:</strong> <span className="success">{product.total_stock} {product.unit}</span><br/><strong>Lokasi:</strong> {product.locations||'-'}</p><div className="field"><label>Lokasi transaksi</label><select value={loc} onChange={e=>setLoc(e.target.value)}>{locations.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select></div><div className="field" style={{marginTop:10}}><label>Qty</label><input type="number" min="1" value={qty} onChange={e=>setQty(Number(e.target.value))}/></div><div className="big-actions"><button className="btn btn-green" onClick={()=>move('IN')}>+ Barang Masuk</button><button className="btn btn-red" onClick={()=>move('OUT')}>− Barang Keluar</button></div></>:<div className="empty">Scan barcode untuk menampilkan produk.</div>}{msg&&<div className={msg.includes('berhasil')?'notice':'notice error'}>{msg}</div>}</section></div></>}
